// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://catyvpgbqhudujgnwdzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdHl2cGdicWh1ZHVqZ253ZHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzMyMTAsImV4cCI6MjA3NDE0OTIxMH0.vZ-y_rXCIbVGvKjKev-ia_o4iC0DQ86vVXldH1pISyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});